# Form implementation generated from reading ui file 'Liegeplatzdaten.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmLiegeplatzerfassung(object):
    def setupUi(self, frmLiegeplatzerfassung):
        frmLiegeplatzerfassung.setObjectName("frmLiegeplatzerfassung")
        frmLiegeplatzerfassung.resize(752, 468)
        self.txtBezeichnung = QtWidgets.QTextEdit(frmLiegeplatzerfassung)
        self.txtBezeichnung.setGeometry(QtCore.QRect(150, 50, 181, 31))
        self.txtBezeichnung.setObjectName("txtBezeichnung")
        self.txtLaenge = QtWidgets.QTextEdit(frmLiegeplatzerfassung)
        self.txtLaenge.setGeometry(QtCore.QRect(150, 110, 181, 31))
        self.txtLaenge.setObjectName("txtLaenge")
        self.txtBreite = QtWidgets.QTextEdit(frmLiegeplatzerfassung)
        self.txtBreite.setGeometry(QtCore.QRect(150, 170, 181, 31))
        self.txtBreite.setObjectName("txtBreite")
        self.txtWassertiefe = QtWidgets.QTextEdit(frmLiegeplatzerfassung)
        self.txtWassertiefe.setGeometry(QtCore.QRect(150, 230, 181, 31))
        self.txtWassertiefe.setObjectName("txtWassertiefe")
        self.cbStatus = QtWidgets.QComboBox(frmLiegeplatzerfassung)
        self.cbStatus.setGeometry(QtCore.QRect(150, 290, 181, 31))
        self.cbStatus.setObjectName("cbStatus")
        self.cbStatus.addItem("")
        self.cbStatus.addItem("")
        self.cbStatus.addItem("")
        self.cbStatus.addItem("")
        self.btnSave = QtWidgets.QPushButton(frmLiegeplatzerfassung)
        self.btnSave.setGeometry(QtCore.QRect(150, 350, 181, 61))
        self.btnSave.setObjectName("btnSave")
        self.btnNew = QtWidgets.QPushButton(frmLiegeplatzerfassung)
        self.btnNew.setGeometry(QtCore.QRect(350, 350, 181, 61))
        self.btnNew.setObjectName("btnNew")
        self.btnClose = QtWidgets.QPushButton(frmLiegeplatzerfassung)
        self.btnClose.setGeometry(QtCore.QRect(550, 350, 181, 61))
        self.btnClose.setObjectName("btnClose")
        self.lblBezeichnung = QtWidgets.QLabel(frmLiegeplatzerfassung)
        self.lblBezeichnung.setGeometry(QtCore.QRect(40, 65, 81, 20))
        self.lblBezeichnung.setObjectName("Bezeichnung")
        self.lblLaenge = QtWidgets.QLabel(frmLiegeplatzerfassung)
        self.lblLaenge.setGeometry(QtCore.QRect(55, 125, 61, 20))
        self.lblLaenge.setObjectName("Laenge")
        self.lblBreite = QtWidgets.QLabel(frmLiegeplatzerfassung)
        self.lblBreite.setGeometry(QtCore.QRect(56, 185, 61, 20))
        self.lblBreite.setObjectName("Breite")
        self.lblWassertiefe = QtWidgets.QLabel(frmLiegeplatzerfassung)
        self.lblWassertiefe.setGeometry(QtCore.QRect(20, 245, 101, 20))
        self.lblWassertiefe.setObjectName("Wassertiefe")
        self.lblStatus = QtWidgets.QLabel(frmLiegeplatzerfassung)
        self.lblStatus.setGeometry(QtCore.QRect(75, 305, 49, 16))
        self.lblStatus.setObjectName("Status")
        self.lblBild = QtWidgets.QLabel(frmLiegeplatzerfassung)
        self.lblBild.setGeometry(QtCore.QRect(380, 65, 49, 16))
        self.lblBild.setObjectName("Bild")
        self.lblDasBild = QtWidgets.QLabel(frmLiegeplatzerfassung)
        self.lblDasBild.setGeometry(QtCore.QRect(430, 50, 301, 251))
        self.lblDasBild.setText("")
        self.lblDasBild.setPixmap(QtGui.QPixmap("images.jpg"))
        self.lblDasBild.setScaledContents(True)
        self.lblDasBild.setObjectName("DasBild")

        self.retranslateUi(frmLiegeplatzerfassung)
        self.btnClose.clicked.connect(self.btnClose_click)
        self.btnNew.clicked.connect(self.btnNew_click)
        self.btnSave.clicked.connect(self.btnSave_click)
        QtCore.QMetaObject.connectSlotsByName(frmLiegeplatzerfassung)

    def retranslateUi(self, frmLiegeplatzerfassung):
        _translate = QtCore.QCoreApplication.translate
        frmLiegeplatzerfassung.setWindowTitle(_translate("frmLiegeplatzerfassung", "frmLiegeplatzerfassung"))
        self.btnSave.setText(_translate("frmLiegeplatzerfassung", "Daten speichern"))
        self.btnNew.setText(_translate("frmLiegeplatzerfassung", "Neues Bild"))
        self.btnClose.setText(_translate("frmLiegeplatzerfassung", "Dialog schließen"))
        self.lblBezeichnung.setText(_translate("frmLiegeplatzerfassung", "Bezeichnung :"))
        self.lblLaenge.setText(_translate("frmLiegeplatzerfassung", "Länge (m) :"))
        self.lblBreite.setText(_translate("frmLiegeplatzerfassung", "Breite (m) :"))
        self.lblWassertiefe.setText(_translate("frmLiegeplatzerfassung", "Wassertiefe (cm) :"))
        self.lblStatus.setText(_translate("frmLiegeplatzerfassung", "Status :"))
        self.lblBild.setText(_translate("frmLiegeplatzerfassung", "Bild :"))
