# Form implementation generated from reading ui file 'frm_voice.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 218)
        self.lblText = QtWidgets.QLabel(Form)
        self.lblText.setGeometry(QtCore.QRect(104, 50, 321, 16))
        self.lblText.setObjectName("lblText")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(104, 80, 321, 261))
        self.textEdit.setObjectName("textEdit")
        self.btnRead = QtWidgets.QPushButton(Form)
        self.btnRead.setGeometry(QtCore.QRect(104, 363, 321, 41))
        self.btnRead.setObjectName("btnRead")
        self.btnClose = QtWidgets.QPushButton(Form)
        self.btnClose.setGeometry(QtCore.QRect(550, 363, 111, 41))
        self.btnClose.setObjectName("btnClose")
        self.rbGerman = QtWidgets.QRadioButton(Form)
        self.rbGerman.setGeometry(QtCore.QRect(560, 140, 89, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.rbGerman.setFont(font)
        self.rbGerman.setChecked(True)
        self.rbGerman.setObjectName("rbGerman")
        self.rbEnglish = QtWidgets.QRadioButton(Form)
        self.rbEnglish.setGeometry(QtCore.QRect(560, 190, 89, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.rbEnglish.setFont(font)
        self.rbEnglish.setObjectName("rbEnglish")

        self.retranslateUi(Form)
        self.btnClose.clicked.connect(self.btnClose_click)
        self.btnRead.clicked.connect(self.btnRead_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Form", "Beispiel Sprachausgabe"))
        self.lblText.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#ff0000;\">Geben Sie den Text ein, welcher vorgelesen werden soll!!</span></p></body></html>"))
        self.btnRead.setText(_translate("Form", "Vorlesen"))
        self.btnClose.setText(_translate("Form", "Beenden"))
        self.rbGerman.setText(_translate("Form", "Deutsch"))
        self.rbEnglish.setText(_translate("Form", "Englisch"))
